//
// Created by Admin on 2021/7/16.
//

#ifndef DEMOFFMPEG_VIDEOCONFIGURATION_H
#define DEMOFFMPEG_VIDEOCONFIGURATION_H


#define DEFAULT_HEIGHT  720;
#define DEFAULT_WIDTH  1280;
#define DEFAULT_FPS  30;
#define DEFAULT_VIDEO_MAX_BPS  3000;
#define DEFAULT_VIDEO_MIN_BPS  2000;
#define DEFAULT_VIDEO_IFI  10;
#define DEFAULT_VIDEO_MIME  "video/avc";

#endif //DEMOFFMPEG_VIDEOCONFIGURATION_H
